(wip) Update sponsorship packages to reflect sponsorship prospectus
codebar/manual pull request #43
Opened 2018-07-06 09:09 UTC by despo

2018-07-06 09:26 UTC, KimberleyCook requested changes
Few little comments but other this is awesome, thanks for updating it.

2018-07-06 09:26 UTC, KimberleyCook commented on _posts/2014-12-19-becoming-a-sponsor.md
> +- 1 spots at a codebar workshop or event for your employees
spot instead of spots

2018-07-06 09:26 UTC, KimberleyCook commented on _posts/2014-12-19-becoming-a-sponsor.md
> +- Paying for our infrastructure costs (we pay for most services we use, from hosting our event management application, to email)
I think we should put paying for our infrastructure first in this list. 

And we pay for for all services not most 😂

2018-07-06 09:34 UTC, despo commented on _posts/2014-12-19-becoming-a-sponsor.md
> +- 1 spots at a codebar workshop or event for your employees
Good spot, I did copy paste this from our existing sponsor prospectous as well 🤣

2018-07-06 09:35 UTC, despo commented on _posts/2014-12-19-becoming-a-sponsor.md
> +- Paying for our infrastructure costs (we pay for most services we use, from hosting our event management application, to email)
Good point, I was thinking that too. 👍 
One day, that will change 🤞

2018-07-06 09:42 UTC, KimberleyCook commented on _posts/2014-12-19-becoming-a-sponsor.md
> +- 1 spots at a codebar workshop or event for your employees
oh dear 😂

2018-07-07 11:00 UTC, KimberleyCook approved these changes

2018-07-08 09:17 UTC, merged